# Default values for qiming-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-shanghai.aliyuncs.com/jibudata/qiming-operator
  pullPolicy: Always
  tag: "v1.0.2"

componentImages:
  uiImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/mig-ui
    tag: "v1.0.1"
  discoveryImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/mig-controller
    tag: "v1.0.2"
  migControllerImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/mig-controller
    tag: "v1.0.2"
  resticHelperImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/velero-restic-restore-helper
    tag: "v1.5.3"
  veleroInstallerImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/velero-installer
    tag: "v1.5.3.2"
  hookRunnerImage:
    repository: registry.cn-shanghai.aliyuncs.com/jibudata/hook-runner
    tag: "latest"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

migconfig:
  version: "v1.0.1"
  clientName: "default"
  deploymentMode: "standalone"
  isAdminCluster: false
  isUINodePortEnabled: true
  keys: "trial"

s3Config:
  skipped: false
  name: ""
  provider: "aws"
  accessKey: ""
  secretKey: ""
  bucket: ""
  s3Url: ""
  region: "default"
  
velero:
  enabled: true
  image: registry.cn-shanghai.aliyuncs.com/jibudata/velero:v1.5.3
  plugins: registry.cn-shanghai.aliyuncs.com/jibudata/velero-plugin-for-aws:v1.1.0,registry.cn-shanghai.aliyuncs.com/jibudata/velero-plugin-for-csi:v0.1.2
  useRestic: true
  disableSnapshot: false
  s3ForcePathStyle: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: ui-service
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
